import pytest

from helpers.pdf_report import init_pdf
from test_data.add_ons_data import load_add_ons
from test_data.driving_range_test_data import DrivingRangeTestData as D
from flows.driving_range_flow import DrivingRangeFlow
from flows.home_flow import HomeFlow
from flows.login_flow import LoginFlow
from flows.payment_callback_flow import PaymentCallbackFlow


class TestDrivingRange:

    def _login(self, login_flow: LoginFlow, home_flow: HomeFlow):
        login_flow.open_login()
        login_flow.choose_country(D.COUNTRY_NAME)
        login_flow.enter_phone_number(D.PHONE_NUMBER)
        login_flow.continue_log_in()
        login_flow.choose_verification_method(D.METHOD_VERIFICATION)
        login_flow.verify_page_code_otp()
        login_flow.enter_otp_code(D.OTP, D.COUNTRY_NAME, D.PHONE_NUMBER)
        home_flow.select_sport_if_shown(D.SPORT_TYPE)
        home_flow.enable_notifications_if_shown()
        home_flow.enable_location_if_shown()
        home_flow.dismiss_coachmark_if_shown()
        home_flow.close_whats_new_if_shown()
        home_flow.verify_home()
    
    @pytest.mark.app_reset("clear")
    @pytest.mark.regression
    @pytest.mark.parametrize("TC_ID", ["DR_001", "DR_002", "DR_003"])
    def test_verify_page_explore_driving_range(self, TC_ID, login_flow: LoginFlow, home_flow: HomeFlow, driving_range_flow: DrivingRangeFlow):
        D.load(TC_ID)
        pdf = init_pdf(D.TC_NAME, tc_id=TC_ID)
        self._login(login_flow, home_flow)
        driving_range_flow.open_driving_range(D.MEMBER_TYPE)
        
    @pytest.mark.app_reset("clear")
    @pytest.mark.regression
    @pytest.mark.parametrize("TC_ID", ["DR_004"])
    def test_verify_page_result_search_driving_range_only_swing_pass(self, TC_ID, login_flow: LoginFlow, home_flow: HomeFlow, driving_range_flow: DrivingRangeFlow):
        D.load(TC_ID)
        pdf = init_pdf(D.TC_NAME, tc_id=TC_ID)
        self._login(login_flow, home_flow)
        driving_range_flow.open_driving_range(D.MEMBER_TYPE)
        driving_range_flow.only_swing_pass_partners(D.MEMBER_TYPE)
    
    @pytest.mark.app_reset("clear")
    @pytest.mark.regression
    @pytest.mark.parametrize("TC_ID", ["DR_005"])
    def test_verify_page_result_search_driving_range(self, TC_ID, login_flow: LoginFlow, home_flow: HomeFlow, driving_range_flow: DrivingRangeFlow):
        D.load(TC_ID)
        pdf = init_pdf(D.TC_NAME, tc_id=TC_ID)
        self._login(login_flow, home_flow)
        driving_range_flow.open_driving_range(D.MEMBER_TYPE)
        driving_range_flow.open_search()
        driving_range_flow.search_driving_range(D.SEARCH_KEYWORD)
    
    @pytest.mark.app_reset("clear")
    @pytest.mark.skip
    @pytest.mark.parametrize("TC_ID", ["DR_006"])
    def test_verify_page_driving_range_details(self, TC_ID, login_flow: LoginFlow, home_flow: HomeFlow, driving_range_flow: DrivingRangeFlow):
        D.load(TC_ID)
        pdf = init_pdf(D.TC_NAME, tc_id=TC_ID)
        self._login(login_flow, home_flow)
        driving_range_flow.open_driving_range(D.MEMBER_TYPE)
        driving_range_flow.open_search()
        driving_range_flow.search_driving_range(D.SEARCH_KEYWORD)
        driving_range_flow.open_result(D.VENUE)
        driving_range_flow.see_all_details_sections()
    
    @pytest.mark.app_reset("clear")
    @pytest.mark.regression
    @pytest.mark.parametrize("TC_ID", ["DR_007", "DR_008", "DR_009"])
    def test_verify_featured_promo_swing_pass_driving_range_details(self, TC_ID, login_flow: LoginFlow, home_flow: HomeFlow, driving_range_flow: DrivingRangeFlow):
        D.load(TC_ID)
        pdf = init_pdf(D.TC_NAME, tc_id=TC_ID)
        self._login(login_flow, home_flow)
        driving_range_flow.open_driving_range(D.MEMBER_TYPE)
        driving_range_flow.open_search()
        driving_range_flow.search_driving_range(D.SEARCH_KEYWORD)
        driving_range_flow.open_result(D.VENUE)
        driving_range_flow.verify_button_exclusive_featured_promo(D.MEMBER_TYPE)
    
    @pytest.mark.app_reset("clear")
    @pytest.mark.regression
    @pytest.mark.parametrize("TC_ID", ["DR_010"])
    def test_verify_see_all_featured_promo_driving_range_details(self, TC_ID, login_flow: LoginFlow, home_flow: HomeFlow, driving_range_flow: DrivingRangeFlow):
        D.load(TC_ID)
        pdf = init_pdf(D.TC_NAME, tc_id=TC_ID)
        self._login(login_flow, home_flow)
        driving_range_flow.open_driving_range(D.MEMBER_TYPE)
        driving_range_flow.open_search()
        driving_range_flow.search_driving_range(D.SEARCH_KEYWORD)
        driving_range_flow.open_result(D.VENUE)
        driving_range_flow.open_featured_promos()
    
    @pytest.mark.app_reset("clear")
    @pytest.mark.regression
    @pytest.mark.parametrize("TC_ID", ["DR_011"])
    def test_verify_maximum_bay_driving_range(self, TC_ID, login_flow: LoginFlow, home_flow: HomeFlow, driving_range_flow: DrivingRangeFlow):
        D.load(TC_ID)
        pdf = init_pdf(D.TC_NAME, tc_id=TC_ID)
        self._login(login_flow, home_flow)
        driving_range_flow.open_driving_range(D.MEMBER_TYPE)
        driving_range_flow.open_search()
        driving_range_flow.search_driving_range(D.SEARCH_KEYWORD)
        driving_range_flow.open_result(D.VENUE)
        driving_range_flow.open_calendar()
        driving_range_flow.choose_date(D.BOOKING_DATE)
        driving_range_flow.choose_bay_type(D.BAY_TYPE)
        driving_range_flow.choose_time(D.BOOKING_START_TIME, D.BOOKING_END_TIME)
        driving_range_flow.book_driving_range()
        driving_range_flow.verify_maximum_bays_driving_range(D.NUMBER_OF_BAYS)
    
    @pytest.mark.app_reset("clear")
    @pytest.mark.regression
    @pytest.mark.parametrize("TC_ID", ["DR_012"])
    def test_verify_booking_information_driving_range(self, TC_ID, login_flow: LoginFlow, home_flow: HomeFlow, driving_range_flow: DrivingRangeFlow):
        D.load(TC_ID)
        pdf = init_pdf(D.TC_NAME, tc_id=TC_ID)
        self._login(login_flow, home_flow)
        driving_range_flow.open_driving_range(D.MEMBER_TYPE)
        driving_range_flow.open_search()
        driving_range_flow.search_driving_range(D.SEARCH_KEYWORD)
        driving_range_flow.open_result(D.VENUE)
        driving_range_flow.open_calendar()
        driving_range_flow.choose_date(D.BOOKING_DATE)
        driving_range_flow.choose_bay_type(D.BAY_TYPE)
        driving_range_flow.choose_time(D.BOOKING_START_TIME, D.BOOKING_END_TIME)
        driving_range_flow.book_driving_range()
        driving_range_flow.set_bays(D.NUMBER_OF_BAYS)
        driving_range_flow.confirm_bays()
        driving_range_flow.verify_booking_information(D.PLAYER_NAME, D.BOOKING_DATE, D.BOOKING_START_TIME, D.BOOKING_END_TIME)
    
    @pytest.mark.app_reset("clear")
    @pytest.mark.regression
    @pytest.mark.parametrize("TC_ID", ["DR_013"])
    def test_verify_maximum_balls(self, TC_ID, login_flow: LoginFlow, home_flow: HomeFlow, driving_range_flow: DrivingRangeFlow):
        D.load(TC_ID)
        pdf = init_pdf(D.TC_NAME, tc_id=TC_ID)
        ITEMS = load_add_ons(TC_ID)
        self._login(login_flow, home_flow)
        driving_range_flow.open_driving_range(D.MEMBER_TYPE)
        driving_range_flow.open_search()
        driving_range_flow.search_driving_range(D.SEARCH_KEYWORD)
        driving_range_flow.open_result(D.VENUE)
        driving_range_flow.open_calendar()
        driving_range_flow.choose_date(D.BOOKING_DATE)
        driving_range_flow.choose_bay_type(D.BAY_TYPE)
        driving_range_flow.choose_time(D.BOOKING_START_TIME, D.BOOKING_END_TIME)
        driving_range_flow.book_driving_range()
        driving_range_flow.set_bays(D.NUMBER_OF_BAYS)
        driving_range_flow.confirm_bays()
        driving_range_flow.set_items(ITEMS)
        driving_range_flow.verify_maximum_balls()
    
    @pytest.mark.app_reset("clear")
    @pytest.mark.regression
    @pytest.mark.parametrize("TC_ID", ["DR_014"])
    def test_verify_minimum_balls(self, TC_ID, login_flow: LoginFlow, home_flow: HomeFlow, driving_range_flow: DrivingRangeFlow):
        D.load(TC_ID)
        pdf = init_pdf(D.TC_NAME, tc_id=TC_ID)
        ITEMS = load_add_ons(TC_ID)
        self._login(login_flow, home_flow)
        driving_range_flow.open_driving_range(D.MEMBER_TYPE)
        driving_range_flow.open_search()
        driving_range_flow.search_driving_range(D.SEARCH_KEYWORD)
        driving_range_flow.open_result(D.VENUE)
        driving_range_flow.open_calendar()
        driving_range_flow.choose_date(D.BOOKING_DATE)
        driving_range_flow.choose_bay_type(D.BAY_TYPE)
        driving_range_flow.choose_time(D.BOOKING_START_TIME, D.BOOKING_END_TIME)
        driving_range_flow.book_driving_range()
        driving_range_flow.set_bays(D.NUMBER_OF_BAYS)
        driving_range_flow.confirm_bays()
        driving_range_flow.set_items(ITEMS)
        driving_range_flow.choose_payment_method(D.PAYMENT_METHOD)
        driving_range_flow.pay_now()
        driving_range_flow.verify_minimum_balls()
    
    @pytest.mark.app_reset("clear")
    @pytest.mark.regression
    @pytest.mark.parametrize("TC_ID", ["DR_015", "DR_016", "DR_017"])
    def test_verify_auto_applied_promo_driving_range(self, TC_ID, login_flow: LoginFlow, home_flow: HomeFlow, driving_range_flow: DrivingRangeFlow):
        D.load(TC_ID)
        pdf = init_pdf(D.TC_NAME, tc_id=TC_ID)
        self._login(login_flow, home_flow)
        driving_range_flow.open_driving_range(D.MEMBER_TYPE)
        driving_range_flow.open_search()
        driving_range_flow.search_driving_range(D.SEARCH_KEYWORD)
        driving_range_flow.open_result(D.VENUE)
        driving_range_flow.open_calendar()
        driving_range_flow.choose_date(D.BOOKING_DATE)
        driving_range_flow.choose_bay_type(D.BAY_TYPE)
        driving_range_flow.choose_time(D.BOOKING_START_TIME, D.BOOKING_END_TIME)
        driving_range_flow.book_driving_range()
        driving_range_flow.set_bays(D.NUMBER_OF_BAYS)
        driving_range_flow.confirm_bays()
        driving_range_flow.verify_auto_applied_promo(D.PROMO_NAME)
    
    
    @pytest.mark.app_reset("clear")
    @pytest.mark.regression
    @pytest.mark.parametrize("TC_ID", ["DR_018", "DR_018"])
    def test_book_without_promo_driving_range(self, TC_ID, login_flow: LoginFlow, home_flow: HomeFlow, driving_range_flow: DrivingRangeFlow):
        D.load(TC_ID)
        pdf = init_pdf(D.TC_NAME, tc_id=TC_ID)
        ITEMS = load_add_ons(TC_ID)
        self._login(login_flow, home_flow)
        driving_range_flow.open_driving_range(D.MEMBER_TYPE)
        driving_range_flow.open_search()
        driving_range_flow.search_driving_range(D.SEARCH_KEYWORD)
        driving_range_flow.open_result(D.VENUE)
        driving_range_flow.open_calendar()
        driving_range_flow.choose_date(D.BOOKING_DATE)
        driving_range_flow.choose_bay_type(D.BAY_TYPE)
        driving_range_flow.choose_time(D.BOOKING_START_TIME, D.BOOKING_END_TIME)
        driving_range_flow.book_driving_range()
        driving_range_flow.set_bays(D.NUMBER_OF_BAYS)
        driving_range_flow.confirm_bays()
        driving_range_flow.set_items(ITEMS)
        driving_range_flow.remove_promo()
        driving_range_flow.choose_payment_method(D.PAYMENT_METHOD)
        payment_information = driving_range_flow.get_payment_information_before_payment("0")
        driving_range_flow.pay_now()
        driving_range_flow.verify_payment_success_driving_range(D.PLAYER_NAME, D.BOOKING_DATE, D.BOOKING_START_TIME, D.BOOKING_END_TIME, D.NUMBER_OF_BAYS ,payment_information, D.BAY_TYPE)
        booking_code = driving_range_flow.get_booking_code_after_payment()
        driving_range_flow.open_booking_details()
        driving_range_flow.verify_data_booking_details_without_credit_used(booking_code, D.PLAYER_NAME, D.BOOKING_DATE, D.BOOKING_START_TIME, D.BOOKING_END_TIME, D.NUMBER_OF_BAYS,payment_information, D.BAY_TYPE)
    
    @pytest.mark.app_reset("clear")
    @pytest.mark.regression
    @pytest.mark.parametrize("TC_ID", ["DR_019", "DR_020", "DR_021", "DR_025"])
    def test_book_with_auto_applied_promo_driving_range(self, TC_ID, login_flow: LoginFlow, home_flow: HomeFlow, driving_range_flow: DrivingRangeFlow):
        D.load(TC_ID)
        pdf = init_pdf(D.TC_NAME, tc_id=TC_ID)
        ITEMS = load_add_ons(TC_ID)
        self._login(login_flow, home_flow)
        driving_range_flow.open_driving_range(D.MEMBER_TYPE)
        driving_range_flow.open_search()
        driving_range_flow.search_driving_range(D.SEARCH_KEYWORD)
        driving_range_flow.open_result(D.VENUE)
        driving_range_flow.open_calendar()
        driving_range_flow.choose_date(D.BOOKING_DATE)
        driving_range_flow.choose_bay_type(D.BAY_TYPE)
        driving_range_flow.choose_time(D.BOOKING_START_TIME, D.BOOKING_END_TIME)
        driving_range_flow.book_driving_range()
        driving_range_flow.set_bays(D.NUMBER_OF_BAYS)
        driving_range_flow.confirm_bays()
        driving_range_flow.set_items(ITEMS)
        driving_range_flow.verify_auto_applied_promo(D.PROMO_NAME)
        driving_range_flow.choose_payment_method(D.PAYMENT_METHOD)
        payment_information = driving_range_flow.get_payment_information_before_payment("0")
        driving_range_flow.pay_now()
        driving_range_flow.verify_payment_success_driving_range(D.PLAYER_NAME, D.BOOKING_DATE, D.BOOKING_START_TIME, D.BOOKING_END_TIME, D.NUMBER_OF_BAYS ,payment_information, D.BAY_TYPE)
        booking_code = driving_range_flow.get_booking_code_after_payment()
        driving_range_flow.open_booking_details()
        driving_range_flow.verify_data_booking_details_without_credit_used(booking_code, D.PLAYER_NAME, D.BOOKING_DATE, D.BOOKING_START_TIME, D.BOOKING_END_TIME, D.NUMBER_OF_BAYS,payment_information, D.BAY_TYPE)
    
    @pytest.mark.app_reset("clear")
    @pytest.mark.regression
    @pytest.mark.parametrize("TC_ID", ["DR_023"])
    def test_book_with_apply_redeemed_promo_driving_range(self, TC_ID, login_flow: LoginFlow, home_flow: HomeFlow, driving_range_flow: DrivingRangeFlow):
        D.load(TC_ID)
        pdf = init_pdf(D.TC_NAME, tc_id=TC_ID)
        ITEMS = load_add_ons(TC_ID)
        self._login(login_flow, home_flow)
        driving_range_flow.open_driving_range(D.MEMBER_TYPE)
        driving_range_flow.open_search()
        driving_range_flow.search_driving_range(D.SEARCH_KEYWORD)
        driving_range_flow.open_result(D.VENUE)
        driving_range_flow.open_calendar()
        driving_range_flow.choose_date(D.BOOKING_DATE)
        driving_range_flow.choose_bay_type(D.BAY_TYPE)
        driving_range_flow.choose_time(D.BOOKING_START_TIME, D.BOOKING_END_TIME)
        driving_range_flow.book_driving_range()
        driving_range_flow.set_bays(D.NUMBER_OF_BAYS)
        driving_range_flow.confirm_bays()
        driving_range_flow.set_items(ITEMS)
        driving_range_flow.apply_and_redeem_promo(D.PROMO_NAME, D.PROMO_CODE)
        driving_range_flow.choose_payment_method(D.PAYMENT_METHOD)
        payment_information = driving_range_flow.get_payment_information_before_payment("0")
        driving_range_flow.pay_now()
        driving_range_flow.verify_payment_success_driving_range(D.PLAYER_NAME, D.BOOKING_DATE, D.BOOKING_START_TIME, D.BOOKING_END_TIME, D.NUMBER_OF_BAYS ,payment_information, D.BAY_TYPE)
        booking_code = driving_range_flow.get_booking_code_after_payment()
        driving_range_flow.open_booking_details()
        driving_range_flow.verify_data_booking_details_without_credit_used(booking_code, D.PLAYER_NAME, D.BOOKING_DATE, D.BOOKING_START_TIME, D.BOOKING_END_TIME, D.NUMBER_OF_BAYS,payment_information, D.BAY_TYPE)
            
    @pytest.mark.app_reset("clear")
    @pytest.mark.regression
    @pytest.mark.parametrize("TC_ID", ["DR_022"])
    def test_book_with_change_promo_driving_range(self, TC_ID, login_flow: LoginFlow, home_flow: HomeFlow, driving_range_flow: DrivingRangeFlow):
        D.load(TC_ID)
        pdf = init_pdf(D.TC_NAME, tc_id=TC_ID)
        ITEMS = load_add_ons(TC_ID)
        self._login(login_flow, home_flow)
        driving_range_flow.open_driving_range(D.MEMBER_TYPE)
        driving_range_flow.open_search()
        driving_range_flow.search_driving_range(D.SEARCH_KEYWORD)
        driving_range_flow.open_result(D.VENUE)
        driving_range_flow.open_calendar()
        driving_range_flow.choose_date(D.BOOKING_DATE)
        driving_range_flow.choose_bay_type(D.BAY_TYPE)
        driving_range_flow.choose_time(D.BOOKING_START_TIME, D.BOOKING_END_TIME)
        driving_range_flow.book_driving_range()
        driving_range_flow.set_bays(D.NUMBER_OF_BAYS)
        driving_range_flow.confirm_bays()
        driving_range_flow.set_items(ITEMS)
        driving_range_flow.apply_promo(D.PROMO_NAME)
        driving_range_flow.choose_payment_method(D.PAYMENT_METHOD)
        payment_information = driving_range_flow.get_payment_information_before_payment("0")
        driving_range_flow.pay_now()
        driving_range_flow.verify_payment_success_driving_range(D.PLAYER_NAME, D.BOOKING_DATE, D.BOOKING_START_TIME, D.BOOKING_END_TIME, D.NUMBER_OF_BAYS ,payment_information, D.BAY_TYPE)
        booking_code = driving_range_flow.get_booking_code_after_payment()
        driving_range_flow.open_booking_details()
        driving_range_flow.verify_data_booking_details_without_credit_used(booking_code, D.PLAYER_NAME, D.BOOKING_DATE, D.BOOKING_START_TIME, D.BOOKING_END_TIME, D.NUMBER_OF_BAYS,payment_information, D.BAY_TYPE)
        
    @pytest.mark.app_reset("clear")
    @pytest.mark.regression
    @pytest.mark.parametrize("TC_ID", ["DR_026"])
    def test_book_without_promo_using_credit_driving_range(self, TC_ID, login_flow: LoginFlow, home_flow: HomeFlow, driving_range_flow: DrivingRangeFlow):
        D.load(TC_ID)
        pdf = init_pdf(D.TC_NAME, tc_id=TC_ID)
        ITEMS = load_add_ons(TC_ID)
        self._login(login_flow, home_flow)
        driving_range_flow.open_driving_range(D.MEMBER_TYPE)
        driving_range_flow.open_search()
        driving_range_flow.search_driving_range(D.SEARCH_KEYWORD)
        driving_range_flow.open_result(D.VENUE)
        driving_range_flow.open_calendar()
        driving_range_flow.choose_date(D.BOOKING_DATE)
        driving_range_flow.choose_bay_type(D.BAY_TYPE)
        driving_range_flow.choose_time(D.BOOKING_START_TIME, D.BOOKING_END_TIME)
        driving_range_flow.book_driving_range()
        driving_range_flow.set_bays(D.NUMBER_OF_BAYS)
        driving_range_flow.confirm_bays()
        driving_range_flow.set_items(ITEMS)
        driving_range_flow.remove_promo()
        driving_range_flow.use_swing_credits()
        driving_range_flow.choose_payment_method(D.PAYMENT_METHOD)
        payment_information = driving_range_flow.get_payment_information_before_payment("1")
        driving_range_flow.pay_now()
        driving_range_flow.verify_payment_success_driving_range(D.PLAYER_NAME, D.BOOKING_DATE, D.BOOKING_START_TIME, D.BOOKING_END_TIME, D.NUMBER_OF_BAYS ,payment_information, D.BAY_TYPE)
        booking_code = driving_range_flow.get_booking_code_after_payment()
        driving_range_flow.open_booking_details()
        driving_range_flow.verify_data_booking_details_with_credit_used(booking_code, D.PLAYER_NAME, D.BOOKING_DATE, D.BOOKING_START_TIME, D.BOOKING_END_TIME, D.NUMBER_OF_BAYS,payment_information, D.BAY_TYPE)
        driving_range_flow.back_to_activity()
        driving_range_flow.open_home_tab()
        driving_range_flow.open_swing_credits()
        driving_range_flow.open_swing_credit_history()
        driving_range_flow.verify_used_credit_booking_code(booking_code, payment_information["used_credit"])
    
    @pytest.mark.app_reset("clear")
    @pytest.mark.regression
    @pytest.mark.parametrize("TC_ID", ["DR_027"])
    def test_book_without_promo_using_credit_driving_range_payment_credit_card(self, TC_ID, login_flow: LoginFlow, home_flow: HomeFlow, driving_range_flow: DrivingRangeFlow):
        D.load(TC_ID)
        pdf = init_pdf(D.TC_NAME, tc_id=TC_ID)
        ITEMS = load_add_ons(TC_ID)
        self._login(login_flow, home_flow)
        driving_range_flow.open_driving_range(D.MEMBER_TYPE)
        driving_range_flow.open_search()
        driving_range_flow.search_driving_range(D.SEARCH_KEYWORD)
        driving_range_flow.open_result(D.VENUE)
        driving_range_flow.open_calendar()
        driving_range_flow.choose_date(D.BOOKING_DATE)
        driving_range_flow.choose_bay_type(D.BAY_TYPE)
        driving_range_flow.choose_time(D.BOOKING_START_TIME, D.BOOKING_END_TIME)
        driving_range_flow.book_driving_range()
        driving_range_flow.set_bays(D.NUMBER_OF_BAYS)
        driving_range_flow.confirm_bays()
        driving_range_flow.set_items(ITEMS)
        driving_range_flow.remove_promo()
        driving_range_flow.use_swing_credits()
        driving_range_flow.choose_payment_method(D.PAYMENT_METHOD)
        payment_information = driving_range_flow.get_payment_information_before_payment("1")
        driving_range_flow.pay_now()
        driving_range_flow.verify_payment_success_driving_range(D.PLAYER_NAME, D.BOOKING_DATE, D.BOOKING_START_TIME, D.BOOKING_END_TIME, D.NUMBER_OF_BAYS ,payment_information, D.BAY_TYPE)
        booking_code = driving_range_flow.get_booking_code_after_payment()
        driving_range_flow.open_booking_details()
        driving_range_flow.verify_data_booking_details_with_credit_used(booking_code, D.PLAYER_NAME, D.BOOKING_DATE, D.BOOKING_START_TIME, D.BOOKING_END_TIME, D.NUMBER_OF_BAYS,payment_information, D.BAY_TYPE)
        driving_range_flow.back_to_activity()
        driving_range_flow.open_home_tab()
        driving_range_flow.open_swing_credits()
        driving_range_flow.open_swing_credit_history()
        driving_range_flow.verify_used_credit_booking_code(booking_code, payment_information["used_credit"])

    def _open_regression_booking(self, driving_range_flow: DrivingRangeFlow):
        driving_range_flow.open_driving_range(D.MEMBER_TYPE)
        driving_range_flow.open_search()
        driving_range_flow.search_driving_range(D.SEARCH_KEYWORD)
        driving_range_flow.open_result(D.VENUE)
        driving_range_flow.open_calendar()
        driving_range_flow.choose_date(D.BOOKING_DATE)
        driving_range_flow.choose_bay_type(D.BAY_TYPE)
        driving_range_flow.choose_time(D.BOOKING_START_TIME, D.BOOKING_END_TIME)
        driving_range_flow.book_driving_range()
        driving_range_flow.set_bays(D.NUMBER_OF_BAYS)
        driving_range_flow.confirm_bays()
        driving_range_flow.remove_promo()

    def _verify_regression_booking(self, driving_range_flow: DrivingRangeFlow, payment_callback_flow: PaymentCallbackFlow, payment_information):
        driving_range_flow.verify_payment_success_driving_range(D.PLAYER_NAME, D.BOOKING_DATE, D.BOOKING_START_TIME, D.BOOKING_END_TIME, D.NUMBER_OF_BAYS, payment_information, D.BAY_TYPE)
        booking_code = driving_range_flow.get_booking_code_after_payment()
        driving_range_flow.open_booking_details()
        driving_range_flow.verify_data_booking_details_without_credit_used(booking_code, D.PLAYER_NAME, D.BOOKING_DATE, D.BOOKING_START_TIME, D.BOOKING_END_TIME, D.NUMBER_OF_BAYS, payment_information, D.BAY_TYPE)
        payment_callback_flow.verify_existing_payment_callback(booking_code)

    @pytest.mark.app_reset("clear")
    @pytest.mark.regression_existing
    @pytest.mark.parametrize("TC_ID", ["DR_REGRESS_GSA_001"])
    def test_regression_existing_book_driving_range_with_credit_card(self, TC_ID, login_flow: LoginFlow, home_flow: HomeFlow, driving_range_flow: DrivingRangeFlow, payment_callback_flow: PaymentCallbackFlow):
        D.load(TC_ID)
        pdf = init_pdf(D.TC_NAME, tc_id=TC_ID)
        self._login(login_flow, home_flow)
        self._open_regression_booking(driving_range_flow)
        driving_range_flow.link_new_credit_card(D.PLAYER_NAME, D.CARD_NUMBER, D.CARD_EXPIRY, D.CARD_CVV, D.CARD_OTP)
        payment_information = driving_range_flow.get_payment_information_before_payment("0")
        driving_range_flow.pay_now_with_credit_card(D.CARD_CVV, D.CARD_OTP)
        self._verify_regression_booking(driving_range_flow, payment_callback_flow, payment_information)

    @pytest.mark.app_reset("clear")
    @pytest.mark.regression_existing
    @pytest.mark.parametrize("TC_ID", ["DR_REGRESS_GSA_002", "DR_REGRESS_GSA_003", "DR_REGRESS_GSA_004", "DR_REGRESS_GSA_005", "DR_REGRESS_GSA_006", "DR_REGRESS_GSA_007", "DR_REGRESS_GSA_008", "DR_REGRESS_GSA_009", "DR_REGRESS_GSA_010", "DR_REGRESS_GSA_011", "DR_REGRESS_GSA_012", "DR_REGRESS_GSA_013", "DR_REGRESS_GSA_014"])
    def test_regression_existing_book_driving_range_by_payment_method(self, TC_ID, login_flow: LoginFlow, home_flow: HomeFlow, driving_range_flow: DrivingRangeFlow, payment_callback_flow: PaymentCallbackFlow):
        D.load(TC_ID)
        pdf = init_pdf(D.TC_NAME, tc_id=TC_ID)
        self._login(login_flow, home_flow)
        self._open_regression_booking(driving_range_flow)
        driving_range_flow.choose_payment_method(D.PAYMENT_METHOD)
        payment_information = driving_range_flow.get_payment_information_before_payment("0")
        driving_range_flow.pay_now()
        self._verify_regression_booking(driving_range_flow, payment_callback_flow, payment_information)
