class CardLinkedSuccessLocators:
    EL_HEADER_VISA = '//XCUIElementTypeOther[@name="VISA"]'
    BTN_CLOSE = '//XCUIElementTypeOther[@name="VISA"]/preceding-sibling::XCUIElementTypeButton[1]'
    BTN_REFRESH = '//XCUIElementTypeOther[@name="VISA"]/following-sibling::XCUIElementTypeButton[1]'
    EL_SUCCESS_PAGE = '//XCUIElementTypeOther[@name="Swing - Success"]'
    IMG_SUCCESS = '//XCUIElementTypeImage[@name="success"]'
    TXT_SUCCESS_TITLE = '//XCUIElementTypeStaticText[@name="Card successfully linked"]'
    TXT_SUCCESS_MESSAGE = '//XCUIElementTypeStaticText[@name="Close this page to continue your payment."]'
    EL_CONTENT_INFORMATION = '//XCUIElementTypeOther[@name="content information"]'
    LINK_GO_TO_HOME = '//XCUIElementTypeLink[@name="go to home"]'
    BTN_COUNTRY = '//XCUIElementTypeButton[contains(@name,"Indonesia")]'
    LINK_PHONE = '//XCUIElementTypeLink[starts-with(@name,"+62")]'
    LINK_EMAIL = '//XCUIElementTypeLink[@name="team@getswing.app"]'
    TXT_COMPANY = '//XCUIElementTypeStaticText[@name="Company"]'
    TXT_SUPPORT = '//XCUIElementTypeStaticText[@name="Support"]'
    TXT_SOCIAL = '//XCUIElementTypeStaticText[@name="Social"]'
    TXT_GET_THE_APP = '//XCUIElementTypeStaticText[@name="Get the app"]'
    LINK_HOME = '//XCUIElementTypeLink[@name="Home"]'
    LINK_ABOUT_US = '//XCUIElementTypeLink[@name="About us"]'
    LINK_CAREERS = '//XCUIElementTypeLink[@name="Careers"]'
    LINK_FUTURE_PLANS = '//XCUIElementTypeLink[@name="Future plans"]'
    LINK_CONTACT_US = '//XCUIElementTypeLink[@name="Contact us"]'
    LINK_TERMS_CONDITIONS = '//XCUIElementTypeLink[@name="Terms & conditions"]'
    LINK_PRIVACY_POLICY = '//XCUIElementTypeLink[@name="Privacy policy"]'
    LINK_INSTAGRAM = '//XCUIElementTypeLink[@name="Instagram"]'
    LINK_TIKTOK = '//XCUIElementTypeLink[@name="TikTok"]'
    LINK_APP_STORE = '//XCUIElementTypeLink[@name="app store download"]'
    LINK_PLAY_STORE = '//XCUIElementTypeLink[@name="play store download"]'
    LINK_BY_NAME = '//XCUIElementTypeLink[@name="{}"]'
