class HomeLocators:
    EL_SPORT_BUTTON = '//XCUIElementTypeOther[@name="home_app_bar_sport_option_button"]'
    EL_COUNTRY_BUTTON = '//XCUIElementTypeOther[@name="home_app_bar_change_country_button"]'
    TXT_SELECT_COUNTRY = '//*[@name="Select country"]'
    IMG_REGION_BY_COUNTRY = '//XCUIElementTypeImage[@name="{}"]'
    BTN_CLOSE_SELECT_COUNTRY = '//*[@name="Select country"]/following-sibling::XCUIElementTypeButton[1]'
    EL_SEARCH_BUTTON = '//XCUIElementTypeOther[@name="home_app_bar_search_button"]'
    EL_NOTIFICATION_BUTTON = '//XCUIElementTypeOther[@name="home_app_bar_notification_button"]'
    BTN_SEARCH = '//XCUIElementTypeOther[@name="home_app_bar_search_button"]/following-sibling::XCUIElementTypeButton[1]'
    BTN_NOTIFICATION = '//XCUIElementTypeOther[@name="home_app_bar_notification_button"]/following-sibling::XCUIElementTypeButton[1]'
    IMG_CATEGORY = '//XCUIElementTypeImage[@name="{}"]'
    IMG_TEE_TIME = '//XCUIElementTypeImage[@name="Tee time"]'
    IMG_DRIVING_RANGE = '//XCUIElementTypeImage[@name="Driving range"]'
    IMG_EVENTS = '//XCUIElementTypeImage[@name="Events"]'
    IMG_MARKETPLACE = '//XCUIElementTypeImage[@name="Marketplace"]'
    IMG_SWING_PASS_BANNER = '//XCUIElementTypeImage[starts-with(@name,"Get access to exclusive promos")]'
    TXT_JOIN_SWING_PASS = '//XCUIElementTypeStaticText[@name="Join Swing Pass"]'
    card_swing_pass = '//*[contains(@name,"Renews on") or contains(@name,"Ends on")]'
    EL_MEMBERSHIP_CARD = '//XCUIElementTypeOther[starts-with(@name,"Renews on")]'
    EL_CREDITS_CARD = '//XCUIElementTypeOther[contains(@name,"credits")]'
    TXT_UPDATES_TITLE = '//XCUIElementTypeStaticText[@name="home_banner_updates_title"]'
    LIST_BANNER_CARDS = '//XCUIElementTypeImage[starts-with(@name,"home_banner_card_")]'
    IMG_BANNER_CARD = '//XCUIElementTypeImage[@name="home_banner_card_{}"]'
    IMG_BANNER_BY_LABEL = '//XCUIElementTypeImage[starts-with(@name,"home_banner_card_") and @label="{}"]'
    TXT_EXPLORE_TITLE = '//XCUIElementTypeStaticText[starts-with(@name,"Explore")]'
    BTN_SEE_ALL = '//XCUIElementTypeButton[@name="See all"]'
    LIST_EXPLORE_PRICE_CARDS = '//XCUIElementTypeOther[@name="product_explore_card_final_price"]'
    EL_EXPLORE_CARD = '//XCUIElementTypeOther[contains(@name,"{}")]'
    IMG_SAVE_BADGE = '//XCUIElementTypeImage[@name="product_explore_card_save_badge"]'
    TAB_HOME = '//XCUIElementTypeButton[starts-with(@name,"Home")]'
    TAB_ACTIVITY = '//XCUIElementTypeButton[starts-with(@name,"Activity")]'
    TAB_ACCOUNT = '//XCUIElementTypeButton[starts-with(@name,"Account")]'
    TAB_BY_NAME = '//XCUIElementTypeButton[starts-with(@name,"{}")]'
    LIST_MAIN_SCROLL = '(//XCUIElementTypeScrollView)[1]'
    LIST_BANNER_SCROLL = '(//XCUIElementTypeScrollView)[2]'
    LIST_EXPLORE_SCROLL = '(//XCUIElementTypeScrollView)[3]'
