class PaymentMethodLocators:
    EL_HEADER = '//XCUIElementTypeOther[@name="Select payment method"]'
    BTN_BACK = '//XCUIElementTypeOther[@name="Select payment method"]/preceding-sibling::XCUIElementTypeButton[1]'
    TXT_SECTION_BY_NAME = '//XCUIElementTypeStaticText[@name="{}"]'
    TXT_CREDIT_CARDS = '//XCUIElementTypeStaticText[@name="Credit cards"]'
    TXT_QRIS_SECTION = '//XCUIElementTypeStaticText[@name="QRIS"]'
    TXT_EWALLETS_SECTION = '//XCUIElementTypeStaticText[@name="E-wallets"]'
    TXT_VIRTUAL_ACCOUNTS_SECTION = '//XCUIElementTypeStaticText[@name="Virtual accounts"]'
    IMG_METHOD_BY_NAME = '//XCUIElementTypeImage[@name="{}"]'
    IMG_QRIS = '//XCUIElementTypeImage[@name="QRIS"]'
    IMG_DANA = '//XCUIElementTypeImage[@name="DANA"]'
    LIST_CREDIT_CARDS = '//XCUIElementTypeImage[starts-with(@name,"VISA")]'
    BTN_ADD_CREDIT_CARD = '//XCUIElementTypeButton[@name="Add credit card"]'
    BTN_CONNECT = '//XCUIElementTypeButton[@name="Connect"]'
