class RegistrationConfirmationLocators:
    EL_HEADER = '//XCUIElementTypeOther[@name="Registration confirmation"]'
    BTN_BACK = '//XCUIElementTypeOther[@name="Registration confirmation"]/preceding-sibling::XCUIElementTypeButton[1]'
    TXT_EVENT_NAME = '//XCUIElementTypeStaticText[@name="{}"]'
    TXT_EVENT_NAME_STARTS = '//XCUIElementTypeStaticText[starts-with(@name,"{}")]'
    TXT_ROW_BY_LABEL = '//XCUIElementTypeStaticText[starts-with(@name,"{}")]'
    TXT_DATE_ROW = '//XCUIElementTypeStaticText[starts-with(@name,"Date")]'
    TXT_STARTING_TIME_ROW = '//XCUIElementTypeStaticText[starts-with(@name,"Starting Time")]'
    TXT_VENUE_ROW = '//XCUIElementTypeStaticText[starts-with(@name,"Venue")]'
    TXT_PLAYER_ROW = '//XCUIElementTypeStaticText[starts-with(@name,"Player\n")]'
    TXT_REGISTRATION_TYPE = '//XCUIElementTypeStaticText[@name="Standard registration"]'
    BTN_CHANGE_REGISTRATION_TYPE = '//XCUIElementTypeStaticText[@name="Standard registration"]/following-sibling::XCUIElementTypeButton[1]'
    TXT_GROUP_REGISTRATION_HINT = '//XCUIElementTypeStaticText[starts-with(@name,"Adding a Swing Pass member?")]'
    IMG_PLAYER_BY_NAME = '//XCUIElementTypeImage[starts-with(@name,"{}") and not(contains(@name,"Registration fee"))]'
    LIST_PLAYERS = '//XCUIElementTypeImage[contains(@name,"Swing Pass member") or contains(@name,"Manually added player")]'
    EL_PROMO_BY_PLAYER = '//XCUIElementTypeImage[starts-with(@name,"{}") and not(contains(@name,"Registration fee"))]/following-sibling::XCUIElementTypeOther[XCUIElementTypeOther[@name="Apply a promo"]]'
    EL_PLAYER_DETAILS_BY_PLAYER = '//XCUIElementTypeImage[starts-with(@name,"{}") and not(contains(@name,"Registration fee"))]/following-sibling::XCUIElementTypeOther//XCUIElementTypeOther[contains(@name, "player details")]'
    IMG_CHANGE_PLAYER_BY_NAME = '//XCUIElementTypeImage[starts-with(@name,"{}") and not(contains(@name,"Registration fee"))]/following-sibling::XCUIElementTypeImage[@name="Change player"]'
    IMG_REMOVE_PLAYER_BY_NAME = '//XCUIElementTypeImage[starts-with(@name,"{}") and not(contains(@name,"Registration fee"))]/following-sibling::XCUIElementTypeImage[@name="Remove player"]'
    EL_APPLY_PROMO = '//XCUIElementTypeOther[@name="Apply a promo"]'
    EL_FILL_PLAYER_DETAILS = '//XCUIElementTypeOther[@name="Fill in player details"]'
    SWITCH_USE_CREDITS = '//XCUIElementTypeSwitch[starts-with(@name,"Use ")]'
    BTN_ADD_PLAYER = '//XCUIElementTypeButton[@name="Add a player"]'
    IMG_NOTE_INPUT = '//XCUIElementTypeImage[@name="tournament_registration_checkout_note_input"]'
    TXT_PROMO_BALANCE_NOTE = '//XCUIElementTypeStaticText[starts-with(@name,"Using a promo for others")]'
    TXT_SELECT_FLIGHT = '//XCUIElementTypeStaticText[@name="Select flight"]'
    EL_FLIGHT_BY_NAME = '//XCUIElementTypeOther[@name="{}"]'
    SWITCH_FLIGHT_BY_NAME = '//XCUIElementTypeOther[@name="{}"]/following-sibling::XCUIElementTypeSwitch[1]'
    LIST_UNASSIGNED_SLOTS = '//XCUIElementTypeImage[@name="Unassigned"]'
    EL_ORGANIZER_ARRANGE = '//XCUIElementTypeOther[starts-with(@name,"Don\'t know which flight")]'
    SWITCH_ORGANIZER_ARRANGE = '//XCUIElementTypeOther[starts-with(@name,"Don\'t know which flight")]/following-sibling::XCUIElementTypeSwitch[1]'
    TXT_FLIGHT_NOTE = '//XCUIElementTypeStaticText[starts-with(@name,"Flight arrangement can always be changed")]'
    TXT_TERMS_TITLE = '//XCUIElementTypeStaticText[@name="Terms & conditions"]'
    TXT_PRICE_DETAILS_TITLE = '//XCUIElementTypeStaticText[@name="Price details"]'
    IMG_PRICE_LINE_BY_PLAYER = '//XCUIElementTypeImage[starts-with(@name,"{}") and contains(@name,"Registration fee")]'
    TXT_PROCESSING_FEE = '//XCUIElementTypeStaticText[starts-with(@name,"Processing fee")]'
    TXT_TOTAL_PAYMENT = '//XCUIElementTypeStaticText[starts-with(@name,"Total payment")]'
    EL_EARNED_CREDITS = '//XCUIElementTypeOther[starts-with(@name,"+ ")]'
    IMG_PAYMENT_METHOD = '//XCUIElementTypeImage[@name="{}"]'
    BTN_CHANGE_PAYMENT = '//XCUIElementTypeStaticText[@name="Price details"]/following-sibling::XCUIElementTypeOther[last()]/XCUIElementTypeButton'
    BTN_PAY_NOW = '//XCUIElementTypeButton[@name="Pay now"]'
    EL_TOTAL_PRICE = '//XCUIElementTypeOther[starts-with(@name,"Rp.") and not(contains(@name,"&#10;"))]'
    LIST_PACKAGES = '//XCUIElementTypeOther[substring(@name, string-length(@name) - 5)="player" or substring(@name, string-length(@name) - 6)="players"]'
    EL_PACKAGE_BY_NAME = '//XCUIElementTypeOther[starts-with(@name,"{}") and contains(@name," player")]'
    LIST_PLAYERS_BY_PACKAGE = '//XCUIElementTypeOther[starts-with(@name,"{}") and contains(@name," player")]/following-sibling::XCUIElementTypeOther//XCUIElementTypeImage[contains(@name,"Swing Pass member") or contains(@name,"Manually added player") or contains(@name,"Swing player")]'
    BTN_ADD_PLAYER_BY_PACKAGE = '//XCUIElementTypeOther[starts-with(@name,"{}") and contains(@name," player")]/following-sibling::XCUIElementTypeOther//XCUIElementTypeButton[@name="Add a player"]'
    SWITCH_USE_CREDITS_BY_PLAYER = '//XCUIElementTypeImage[starts-with(@name,"{}") and not(contains(@name,"Registration fee"))]/following-sibling::XCUIElementTypeSwitch[1]'
    TXT_PAY_NOW_TERMS = '//XCUIElementTypeStaticText[starts-with(@name,"By tapping the")]'
    BUTTON_REMOVE_PLAYER = '//XCUIElementTypeImage[@name="Remove player"]'
