class TeeTimeBookingConfirmationLocators:
    EL_HEADER = '//XCUIElementTypeOther[@name="Booking confirmation"]'
    BTN_BACK = '//XCUIElementTypeOther[@name="Booking confirmation"]/preceding-sibling::XCUIElementTypeButton[1]'
    TXT_VENUE_NAME = '//XCUIElementTypeStaticText[@name="{}"]'
    TXT_ROW_BY_LABEL = '//XCUIElementTypeStaticText[starts-with(@name,"{}")]'
    TXT_DATE_ROW = '//XCUIElementTypeImage[starts-with(@name,"Date")]'
    TXT_SESSION_ROW = '//XCUIElementTypeImage[starts-with(@name,"Session")]'
    TXT_PREFERRED_TIME_ROW = '//XCUIElementTypeImage[starts-with(@name,"Preferred time")]'
    TXT_BOOKING_TYPE = '//XCUIElementTypeStaticText[@name="Standard Booking"]'
    TXT_BOOKING_TYPE_BY_NAME = '//XCUIElementTypeStaticText[@name="{}"]'
    BTN_CHANGE_BOOKING_TYPE = '//XCUIElementTypeStaticText[@name="Standard Booking"]/following-sibling::XCUIElementTypeButton[1]'
    TXT_GROUP_BOOKING_HINT = '//XCUIElementTypeStaticText[starts-with(@name,"Adding a Swing Pass member?")]'
    IMG_PLAYER_BY_NAME = '//*[starts-with(@name,"{}") and not(contains(@name,"Publish"))]'
    LIST_PLAYERS = '//XCUIElementTypeImage[contains(@name,"Swing player") or contains(@name,"Swing Pass member") or contains(@name,"Manually added player")]'
    EL_PROMO_BY_PLAYER = '//XCUIElementTypeImage[starts-with(@name,"{}") and not(contains(@name,"Publish"))]/following-sibling::XCUIElementTypeOther[not(XCUIElementTypeOther[contains(@name,"add-ons")])][1]/XCUIElementTypeOther[1]'
    EL_ADDONS_BY_PLAYER = '//XCUIElementTypeImage[starts-with(@name,"{}") and not(contains(@name,"Publish"))]/following-sibling::XCUIElementTypeOther[XCUIElementTypeOther[contains(@name,"add-ons")]][1]/XCUIElementTypeOther[contains(@name,"add-ons")]'
    IMG_CHANGE_PLAYER_BY_NAME = '//XCUIElementTypeImage[starts-with(@name,"{}") and not(contains(@name,"Publish"))]/following-sibling::XCUIElementTypeImage[@name="Change player"]'
    IMG_REMOVE_PLAYER_BY_NAME = '//XCUIElementTypeImage[starts-with(@name,"{}") and not(contains(@name,"Publish"))]/following-sibling::XCUIElementTypeImage[@name="Remove player"]'
    EL_ADDONS = '//XCUIElementTypeOther[contains(@name,"add-ons")]'
    SWITCH_USE_CREDITS_PLAYER = '//XCUIElementTypeImage[starts-with(@name,"{}")]/following-sibling::XCUIElementTypeSwitch'
    BTN_ADD_PLAYER = '//XCUIElementTypeButton[@name="Add a player"]'
    IMG_NOTE_INPUT = '//XCUIElementTypeImage[@name="tee_time_checkout_note_input"]'
    TXT_PROMO_BALANCE_NOTE = '//XCUIElementTypeStaticText[starts-with(@name,"Using a promo for others")]'
    TXT_TERMS_TITLE = '//XCUIElementTypeStaticText[@name="Terms & conditions"]'
    BTN_SHOW_MORE = '//XCUIElementTypeButton[@name="Show more"]'
    TXT_PRICE_DETAILS_TITLE = '//XCUIElementTypeStaticText[@name="Price details"]'
    IMG_PRICE_LINE_BY_PLAYER = '//XCUIElementTypeImage[starts-with(@name,"{}") and contains(@name,"Publish")]'
    IMG_CREDITS_LINE_BY_PLAYER = '//XCUIElementTypeImage[starts-with(@name,"{}") and contains(@name,"Swing Credits used")]'
    LIST_PRICE_LINES = '//XCUIElementTypeImage[contains(@name,"Publish Rate")]'
    LIST_CREDITS_LINES = '//XCUIElementTypeImage[contains(@name,"Swing Credits used")]'
    LIST_ADDONS = '//XCUIElementTypeOther[contains(@name,"add-ons")]'
    TXT_PRICE_LINE_BY_LABEL = '//XCUIElementTypeStaticText[starts-with(@name,"{}")]'
    TXT_PROCESSING_FEE = '//XCUIElementTypeStaticText[starts-with(@name,"Processing fee")]'
    TXT_TOTAL_PAYMENT = '//XCUIElementTypeStaticText[starts-with(@name,"Total payment")]'
    EL_EARNED_CREDITS = '//XCUIElementTypeOther[starts-with(@name,"+ ")]'
    IMG_PAYMENT_METHOD = '//XCUIElementTypeImage[@name="{}"]'
    BTN_CHANGE_PAYMENT = '//XCUIElementTypeStaticText[@name="Price details"]/following-sibling::XCUIElementTypeOther[last()]/XCUIElementTypeButton' ##'//XCUIElementTypeButton[@name="Change"]'
    BTN_PAY_NOW = '//XCUIElementTypeButton[@name="Pay now"]'
