class GroupBookingConfirmationLocators:
    EL_HEADER = '//XCUIElementTypeOther[@name="Booking confirmation"]'
    TXT_COUNTDOWN = '//XCUIElementTypeStaticText[starts-with(@name,"Please complete group booking in")]'
    TXT_BOOKING_TYPE = '//XCUIElementTypeStaticText[@name="Group Booking"]'
    EL_PLAYER_STATUS = '//XCUIElementTypeImage[starts-with(@name,"{}") and not(contains(@name,"Publish"))]/preceding-sibling::XCUIElementTypeOther[1]'
    EL_PLAYER_READY = '//XCUIElementTypeImage[starts-with(@name,"{}") and not(contains(@name,"Publish"))]/preceding-sibling::XCUIElementTypeOther[1][contains(@name,"Ready!")]'
    EL_PLAYER_WAITING = '//*[starts-with(@name,"{}") and contains(@name, "Waiting to join") and not(contains(@name,"Publish"))]'
    BTN_INVITE_MORE = '//XCUIElementTypeButton[starts-with(@name,"Invite up to")]'
    BTN_IM_READY = '//XCUIElementTypeButton[@name="I\'m ready"]'
    BTN_GO_BACK = '//XCUIElementTypeButton[@name="Go back"]'
    EL_WAITING_HOST = '//XCUIElementTypeOther[starts-with(@name,"Waiting for host and others")]'
    TXT_NO_PAYMENT = '//XCUIElementTypeStaticText[@name="No payment selected"]'
    TXT_HOST_WILL_PAY = '//XCUIElementTypeStaticText[@name="Host will make the payment."]'
    TXT_CANCEL_GROUP_BOOKING = '//XCUIElementTypeStaticText[@name="Cancel group booking"]'
    SWITCH_USE_CREDITS_PLAYER = '//XCUIElementTypeImage[starts-with(@name,"{}") and not(contains(@name,"Publish"))]/following-sibling::XCUIElementTypeSwitch'
    BTN_PAY_NOW = '//XCUIElementTypeButton[@name="Pay now"]'
