class BookingConfirmationLocators:
    EL_HEADER = '//XCUIElementTypeOther[@name="Booking confirmation"]'
    BTN_BACK = '//XCUIElementTypeOther[@name="Booking confirmation"]/preceding-sibling::XCUIElementTypeButton[1]'
    TXT_VENUE_NAME = '//XCUIElementTypeStaticText[@name="{}"]'
    TXT_ROW_BY_LABEL = '//XCUIElementTypeStaticText[starts-with(@name,"{}")]'
    TXT_PLAYER_NAME_ROW = '//XCUIElementTypeStaticText[starts-with(@name,"Player name")]'
    TXT_DATE_ROW = '//XCUIElementTypeStaticText[starts-with(@name,"Date")]'
    TXT_BOOKING_TIME_ROW = '//XCUIElementTypeStaticText[starts-with(@name,"Booking time")]'
    TXT_DURATION_ROW = '//XCUIElementTypeStaticText[starts-with(@name,"Duration")]'
    TXT_NUMBER_OF_BAYS_ROW = '//XCUIElementTypeStaticText[starts-with(@name,"Number of bays")]'
    TXT_BAY_TYPE_ROW = '//XCUIElementTypeStaticText[starts-with(@name,"Bay Type")]'
    TXT_BALLS_TITLE = '//XCUIElementTypeStaticText[@name="How many balls?"]'
    TXT_MINIMUM_BALLS = '//XCUIElementTypeStaticText[starts-with(@name,"Minimum")]'
    LBL_MINIMUM_BALLS_TOASTER = '//XCUIElementTypeImage[contains(@name,"Minimum") and contains(@name,"balls for booking")]'
    LIST_BALL_OPTIONS = '//XCUIElementTypeOther[contains(@name," balls\n")]'
    TXT_ADDONS_TITLE = '//XCUIElementTypeStaticText[@name="Any rentals or add-ons?"]'
    LIST_ADDONS = '//XCUIElementTypeOther[contains(@name," per item\n")]'
    EL_ITEM_BY_NAME = '//XCUIElementTypeOther[starts-with(@name,"{}")]'
    BTN_ITEM_DECREASE = '//XCUIElementTypeOther[contains(@name,"{}")]/following-sibling::XCUIElementTypeButton[1]'
    BTN_ITEM_INCREASE = '//XCUIElementTypeOther[contains(@name,"{}")]/following-sibling::XCUIElementTypeButton[2]'
    IMG_NOTE_INPUT = '//XCUIElementTypeImage[@name="driving_range_checkout_note_input"]'
    TXT_POLICY_TITLE = '//XCUIElementTypeStaticText[@name="Reschedule & cancellation policy"]'
    TXT_TAB_RESCHEDULE = '//XCUIElementTypeStaticText[@name="Reschedule"]'
    TXT_TAB_CANCELLATION = '//XCUIElementTypeStaticText[@name="Cancellation"]'
    BTN_LEARN_MORE = '//XCUIElementTypeButton[@name="Learn more"]'
    TXT_TERMS_TITLE = '//XCUIElementTypeStaticText[@name="Terms & Conditions"]'
    LINK_TERMS = '//XCUIElementTypeLink[starts-with(@name,"Swing")]'
    TXT_PRICE_DETAILS_TITLE = '//XCUIElementTypeStaticText[starts-with(@name,"Price details")]'
    TXT_PRICE_LINE_BY_LABEL = '//XCUIElementTypeStaticText[starts-with(@name,"{}")]'
    EL_PROCESSING_FEE = '//XCUIElementTypeOther[starts-with(@name,"Processing fee")]'
    TXT_TOTAL_PAYMENT = '//XCUIElementTypeStaticText[starts-with(@name,"Total payment")]'
    EL_PROMO_APPLIED = '//XCUIElementTypeOther[contains(@name,"promo auto applied")]'
    BTN_PROMO = '//XCUIElementTypeStaticText[contains(@name,"Price details")]/following-sibling::XCUIElementTypeOther[2]/XCUIElementTypeOther'
    SWITCH_USE_CREDITS = '//XCUIElementTypeSwitch[starts-with(@name,"Use ")]'
    EL_EARNED_CREDITS = '//XCUIElementTypeOther[starts-with(@name,"+ ")]'
    IMG_PAYMENT_METHOD = '//XCUIElementTypeImage[@name="{}"]'
    BTN_CHANGE_PAYMENT = '//XCUIElementTypeButton[@name="Change"]'
    EL_NO_PAYMENT_SELECTED = '//XCUIElementTypeOther[@name="No payment selected"]'
    BTN_SELECT_PAYMENT = '//XCUIElementTypeStaticText[contains(@name,"Price details")]/following-sibling::XCUIElementTypeOther[last()]/XCUIElementTypeButton'
    BTN_PAY_NOW = '//XCUIElementTypeButton[@name="Pay now"]'
    LBL_USED_CREDITS = '//XCUIElementTypeStaticText[starts-with(@name,"Swing Credits")]'
